# Conclusions and Recommendations

{{< var devname >}} is expected to provide an increase in activity to the study area, both for work and leisure. The site provides office, retail, and dining space in a convenient location near the I-15/University Ave. interchange. The site layout offers access from both 1200 South and University Ave., though the latter only indirectly via cross accesses to adjacent developments. This is done to comply with Utah rule R930-6-7 (3)(a) [@utahdepartmentoftransportation2019]: adding a direct access to the site on University Ave. would violate driveway spacing guidelines. This access layout also allows for a parking lot with better circulation compared to having a direct University Ave. access (see @fig-site-plan).

The development of {{< var devname >}} will have little to no effect on the traffic operations of the study area. The added trips to the site do affect intersection control delay and \acr{LOS} for certain movements, but rarely by more than a fraction of a second. There are, however, several already poorly performing movements in the study area due to background traffic alone. Possible improvements could include altered signal timings and/or a raised median, among others, but it is unclear if any improvements would be effective. Due to the relatively low volumes on the poorly-performing movements, it may in fact be desirable to prioritize heavier-trafficked movements to decrease total, rather than average, delay. Therefore, no changes to the study area are explicitly recommended based on this analysis, though a raised median ought to be considered for safety and other reasons.
