project:
  type: book

execute: 
  echo: false
  
book:
  title: "Dream Town"
  subtitle: "Traffic Impact Analysis"
  author: "Hayden Atchley"
  date: today
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - qmd/01_intro.qmd
    - qmd/02_development.qmd
    - qmd/03_study-area.qmd
    - qmd/04_existing.qmd
    # - qmd/05_projected.qmd
    # - qmd/06_access.qmd
    # - qmd/07_analysis.qmd
    # - qmd/08_conclusions.qmd
    - qmd/references.qmd
  appendices: 
    - qmd/appendix/apdx_tripgen.qmd
    - qmd/appendix/apdx_ex_synchro.qmd

bibliography: references.bib

format:
  docx:
    toc: true
    reference-doc: reference.docx
    number-depth: 2
    toc-depth: 2
    csl: asce.csl
  # pdf:
  #   documentclass: scrreprt
  # html:
  #   toc: true


