project:
  type: book

execute: 
  echo: false
  freeze: auto

# knitr:
#   opts_chunk: 
#     ft.keepnext: true
    
book:
  title: "Dream Town Development"
  subtitle: "Traffic Impact Analysis"
  author: "Hayden Atchley"
  date: today
  date-format: "MMMM D, YYYY"
  chapters:
    - index.qmd
    - qmd/01_intro.qmd
    - qmd/02_development.qmd
    - qmd/03_study-area.qmd
    - qmd/04_existing.qmd
    - qmd/05_projected.qmd
    # - qmd/06_access.qmd
    # - qmd/07_analysis.qmd
    # - qmd/08_conclusions.qmd
    - qmd/references.qmd
  appendices: 
    - qmd/appendix/apdx_ex_synchro.qmd
    - qmd/appendix/apdx_signal_timings.qmd
    - qmd/appendix/apdx_tripgen.qmd

class: "CE 664"
firm: "HSL Developers"
bibliography: references.bib
toc: true
lof: true
lot: true
toc-depth: 2
number-depth: 1
csl: asce.csl
filters:
  - lua/acronyms/parse-acronyms.lua
acronyms:
  fromfile: "_acronyms.yml"
  insert_loa: false
  loa_title: ""
  include_unused: false
  insert_links: false
crossref: 
  appendix-delim: "."

format:
  # docx:
  #   reference-doc: reference.docx
  pdf:
    template: template.latex
    titlepage: true
    book: true
    titlepage-background: title_page_background.pdf
    float-placement-figure: htbp
    toc-own-page: true
    footer-left: \hfill
    footer-right: \hfill
    footer-center: \thepage
    classoption: openany
    top-level-division: chapter
    mainfont: "Gentium Book Basic"
    sansfont: "Alte Haas Grotesk"
    monofont: "SauceCodePro NF"
  # html:
  #   toc: true


