project:
  type: book

book:
  title: "664TP"
  author: "Hayden Atchley"
  date: today
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - qmd/intro.qmd
    - qmd/summary.qmd
    - qmd/references.qmd

bibliography: references.bib

format:
  docx:
    toc: true
  pdf:
    documentclass: scrreprt



